package com.ssl.entities;
// Generated 28/02/2017 11:05:58 by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * AutenticationHistory generated by hbm2java
 */
public class AutenticationHistory implements java.io.Serializable
{

    /**
     * 
     */
    private static final long serialVersionUID = -3365926429476269718L;
    
    private int id;
    private Condominium condominium;
    private Employee employee;
    private Userr userr;
    private Boolean accepted;
    private String reason;
    private Date date;

    public AutenticationHistory()
    {
    }

    public AutenticationHistory(int id, Date date)
    {
        this.id = id;
        this.date = date;
    }

    public AutenticationHistory(int id, Condominium condominium, Employee employee, Userr userr, Boolean accepted,
            String reason, Date date)
    {
        this.id = id;
        this.condominium = condominium;
        this.employee = employee;
        this.userr = userr;
        this.accepted = accepted;
        this.reason = reason;
        this.date = date;
    }

    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    public Condominium getCondominium()
    {
        return this.condominium;
    }

    public void setCondominium(Condominium condominium)
    {
        this.condominium = condominium;
    }

    public Employee getEmployee()
    {
        return this.employee;
    }

    public void setEmployee(Employee employee)
    {
        this.employee = employee;
    }

    public Userr getUserr()
    {
        return this.userr;
    }

    public void setUserr(Userr userr)
    {
        this.userr = userr;
    }

    public Boolean getAccepted()
    {
        return this.accepted;
    }

    public void setAccepted(Boolean accepted)
    {
        this.accepted = accepted;
    }

    public String getReason()
    {
        return this.reason;
    }

    public void setReason(String reason)
    {
        this.reason = reason;
    }

    public Date getDate()
    {
        return this.date;
    }

    public void setDate(Date date)
    {
        this.date = date;
    }

}
