package com.ssl.entities;
// default package

// Generated 28/02/2017 22:40:44 by Hibernate Tools 5.2.1.Final

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * AutenticationHistory generated by hbm2java
 */
@Entity
@Table(name = "autentication_history", schema = "dbo")
@DynamicInsert
@DynamicUpdate
public class AutenticationHistory implements Serializable
{

    /**
     * 
     */
    private static final long serialVersionUID = -3365926429476269718L;

    private int id;
    private Condominium condominium;
    private Employee employee;
    private Userr userr;
    private Boolean accepted;
    private String reason;
    private Date date;

    public AutenticationHistory()
    {
    }

    public AutenticationHistory(int id, Date date)
    {
        this.id = id;
        this.date = date;
    }

    public AutenticationHistory(int id, Condominium condominium, Employee employee, Userr userr, Boolean accepted,
            String reason, Date date)
    {
        this.id = id;
        this.condominium = condominium;
        this.employee = employee;
        this.userr = userr;
        this.accepted = accepted;
        this.reason = reason;
        this.date = date;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "condominium_id")
    public Condominium getCondominium()
    {
        return this.condominium;
    }

    public void setCondominium(Condominium condominium)
    {
        this.condominium = condominium;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "employee_id")
    public Employee getEmployee()
    {
        return this.employee;
    }

    public void setEmployee(Employee employee)
    {
        this.employee = employee;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "userr_id")
    public Userr getUserr()
    {
        return this.userr;
    }

    public void setUserr(Userr userr)
    {
        this.userr = userr;
    }

    @Column(name = "accepted")
    public Boolean getAccepted()
    {
        return this.accepted;
    }

    public void setAccepted(Boolean accepted)
    {
        this.accepted = accepted;
    }

    @Column(name = "reason")
    public String getReason()
    {
        return this.reason;
    }

    public void setReason(String reason)
    {
        this.reason = reason;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date_", nullable = false, length = 29)
    public Date getDate()
    {
        return this.date;
    }

    public void setDate(Date date)
    {
        this.date = date;
    }

}
