package com.ssl.entities;
// default package

// Generated 28/02/2017 22:40:44 by Hibernate Tools 5.2.1.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * CondominiumAddress generated by hbm2java
 */
@Entity
@Table(name = "condominium_address", schema = "dbo")
@DynamicInsert
@DynamicUpdate
public class CondominiumAddress implements Serializable
{

    /**
     * 
     */
    private static final long serialVersionUID = -3220932146190126402L;

    private int id;
    private Condominium condominium;
    private String street;
    private int number;
    private String complement;
    private String district;
    private String state;
    private String city;
    private int zipCode;
    private String country;

    public CondominiumAddress()
    {
    }

    public CondominiumAddress(int id, String street, int number, String complement, String district, String state,
            String city, int zipCode, String country)
    {
        this.id = id;
        this.street = street;
        this.number = number;
        this.complement = complement;
        this.district = district;
        this.state = state;
        this.city = city;
        this.zipCode = zipCode;
        this.country = country;
    }

    public CondominiumAddress(int id, Condominium condominium, String street, int number, String complement,
            String district, String state, String city, int zipCode, String country)
    {
        this.id = id;
        this.condominium = condominium;
        this.street = street;
        this.number = number;
        this.complement = complement;
        this.district = district;
        this.state = state;
        this.city = city;
        this.zipCode = zipCode;
        this.country = country;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "condominium_id")
    public Condominium getCondominium()
    {
        return this.condominium;
    }

    public void setCondominium(Condominium condominium)
    {
        this.condominium = condominium;
    }

    @Column(name = "street", nullable = false)
    public String getStreet()
    {
        return this.street;
    }

    public void setStreet(String street)
    {
        this.street = street;
    }

    @Column(name = "number_", nullable = false)
    public int getNumber()
    {
        return this.number;
    }

    public void setNumber(int number)
    {
        this.number = number;
    }

    @Column(name = "complement", nullable = true)
    public String getComplement()
    {
        return this.complement;
    }

    public void setComplement(String complement)
    {
        this.complement = complement;
    }

    @Column(name = "district", nullable = false)
    public String getDistrict()
    {
        return this.district;
    }

    public void setDistrict(String district)
    {
        this.district = district;
    }

    @Column(name = "state_", nullable = false)
    public String getState()
    {
        return this.state;
    }

    public void setState(String state)
    {
        this.state = state;
    }

    @Column(name = "city", nullable = false)
    public String getCity()
    {
        return this.city;
    }

    public void setCity(String city)
    {
        this.city = city;
    }

    @Column(name = "zip_code", nullable = false)
    public int getZipCode()
    {
        return this.zipCode;
    }

    public void setZipCode(int zipCode)
    {
        this.zipCode = zipCode;
    }

    @Column(name = "country", nullable = false)
    public String getCountry()
    {
        return this.country;
    }

    public void setCountry(String country)
    {
        this.country = country;
    }

}
