package com.ssl.entities;
// Generated 28/02/2017 11:05:58 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Condominium generated by hbm2java
 */
public class Condominium implements java.io.Serializable
{

    /**
     * 
     */
    private static final long serialVersionUID = -5940595036721461991L;
    
    private int id;
    private String name;
    private Boolean active;
    private Set<Employee> employees = new HashSet<Employee>(0);
    private Set<Visitor> visitors = new HashSet<Visitor>(0);
    private Set<Userr> userrs = new HashSet<Userr>(0);
    private Set<CondominiumAddress> condominiumAddresses = new HashSet<CondominiumAddress>(0);
    private Set<ScheduledVisit> scheduledVisits = new HashSet<ScheduledVisit>(0);
    private Set<AutenticationHistory> autenticationHistories = new HashSet<AutenticationHistory>(0);
    private Set<PhoneNumberCondominium> phoneNumberCondominiums = new HashSet<PhoneNumberCondominium>(0);

    public Condominium()
    {
    }

    public Condominium(int id, String name)
    {
        this.id = id;
        this.name = name;
    }

    public Condominium(int id, String name, Boolean active, Set<Employee> employees, Set<Visitor> visitors,
            Set<Userr> userrs, Set<CondominiumAddress> condominiumAddresses, Set<ScheduledVisit> scheduledVisits,
            Set<AutenticationHistory> autenticationHistories, Set<PhoneNumberCondominium> phoneNumberCondominiums)
    {
        this.id = id;
        this.name = name;
        this.active = active;
        this.employees = employees;
        this.visitors = visitors;
        this.userrs = userrs;
        this.condominiumAddresses = condominiumAddresses;
        this.scheduledVisits = scheduledVisits;
        this.autenticationHistories = autenticationHistories;
        this.phoneNumberCondominiums = phoneNumberCondominiums;
    }

    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public Boolean getActive()
    {
        return this.active;
    }

    public void setActive(Boolean active)
    {
        this.active = active;
    }

    public Set<Employee> getEmployees()
    {
        return this.employees;
    }

    public void setEmployees(Set<Employee> employees)
    {
        this.employees = employees;
    }

    public Set<Visitor> getVisitors()
    {
        return this.visitors;
    }

    public void setVisitors(Set<Visitor> visitors)
    {
        this.visitors = visitors;
    }

    public Set<Userr> getUserrs()
    {
        return this.userrs;
    }

    public void setUserrs(Set<Userr> userrs)
    {
        this.userrs = userrs;
    }

    public Set<CondominiumAddress> getCondominiumAddresses()
    {
        return this.condominiumAddresses;
    }

    public void setCondominiumAddresses(Set<CondominiumAddress> condominiumAddresses)
    {
        this.condominiumAddresses = condominiumAddresses;
    }

    public Set<ScheduledVisit> getScheduledVisits()
    {
        return this.scheduledVisits;
    }

    public void setScheduledVisits(Set<ScheduledVisit> scheduledVisits)
    {
        this.scheduledVisits = scheduledVisits;
    }

    public Set<AutenticationHistory> getAutenticationHistories()
    {
        return this.autenticationHistories;
    }

    public void setAutenticationHistories(Set<AutenticationHistory> autenticationHistories)
    {
        this.autenticationHistories = autenticationHistories;
    }

    public Set<PhoneNumberCondominium> getPhoneNumberCondominiums()
    {
        return this.phoneNumberCondominiums;
    }

    public void setPhoneNumberCondominiums(Set<PhoneNumberCondominium> phoneNumberCondominiums)
    {
        this.phoneNumberCondominiums = phoneNumberCondominiums;
    }

}
