package com.ssl.entities;
// default package
// Generated 28/02/2017 22:40:44 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", schema = "dbo", uniqueConstraints = @UniqueConstraint(columnNames = "cpf"))
public class Employee implements java.io.Serializable
{

    private int id;
    private Condominium condominium;
    private String name;
    private int cpf;
    private Boolean adm;
    private String email;
    private Set<AutenticationHistory> autenticationHistories = new HashSet<AutenticationHistory>(0);
    private Set<PhoneNumberEmployee> phoneNumberEmployees = new HashSet<PhoneNumberEmployee>(0);

    public Employee()
    {
    }

    public Employee(int id, String name, int cpf, String email)
    {
        this.id = id;
        this.name = name;
        this.cpf = cpf;
        this.email = email;
    }

    public Employee(int id, Condominium condominium, String name, int cpf, Boolean adm, String email,
            Set<AutenticationHistory> autenticationHistories, Set<PhoneNumberEmployee> phoneNumberEmployees)
    {
        this.id = id;
        this.condominium = condominium;
        this.name = name;
        this.cpf = cpf;
        this.adm = adm;
        this.email = email;
        this.autenticationHistories = autenticationHistories;
        this.phoneNumberEmployees = phoneNumberEmployees;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "condominium_id")
    public Condominium getCondominium()
    {
        return this.condominium;
    }

    public void setCondominium(Condominium condominium)
    {
        this.condominium = condominium;
    }

    @Column(name = "name", nullable = false)
    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    @Column(name = "cpf", unique = true, nullable = false)
    public int getCpf()
    {
        return this.cpf;
    }

    public void setCpf(int cpf)
    {
        this.cpf = cpf;
    }

    @Column(name = "adm")
    public Boolean getAdm()
    {
        return this.adm;
    }

    public void setAdm(Boolean adm)
    {
        this.adm = adm;
    }

    @Column(name = "email", nullable = false)
    public String getEmail()
    {
        return this.email;
    }

    public void setEmail(String email)
    {
        this.email = email;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
    public Set<AutenticationHistory> getAutenticationHistories()
    {
        return this.autenticationHistories;
    }

    public void setAutenticationHistories(Set<AutenticationHistory> autenticationHistories)
    {
        this.autenticationHistories = autenticationHistories;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
    public Set<PhoneNumberEmployee> getPhoneNumberEmployees()
    {
        return this.phoneNumberEmployees;
    }

    public void setPhoneNumberEmployees(Set<PhoneNumberEmployee> phoneNumberEmployees)
    {
        this.phoneNumberEmployees = phoneNumberEmployees;
    }

}
