package com.ssl.entities;
// Generated 28/02/2017 11:05:58 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable
{

    /**
     * 
     */
    private static final long serialVersionUID = 3555149641948212561L;
    
    private int id;
    private Condominium condominium;
    private String name;
    private int cpf;
    private Boolean adm;
    private String email;
    private Set<AutenticationHistory> autenticationHistories = new HashSet<AutenticationHistory>(0);
    private Set<PhoneNumberEmployee> phoneNumberEmployees = new HashSet<PhoneNumberEmployee>(0);

    public Employee()
    {
    }

    public Employee(int id, String name, int cpf, String email)
    {
        this.id = id;
        this.name = name;
        this.cpf = cpf;
        this.email = email;
    }

    public Employee(int id, Condominium condominium, String name, int cpf, Boolean adm, String email,
            Set<AutenticationHistory> autenticationHistories, Set<PhoneNumberEmployee> phoneNumberEmployees)
    {
        this.id = id;
        this.condominium = condominium;
        this.name = name;
        this.cpf = cpf;
        this.adm = adm;
        this.email = email;
        this.autenticationHistories = autenticationHistories;
        this.phoneNumberEmployees = phoneNumberEmployees;
    }

    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    public Condominium getCondominium()
    {
        return this.condominium;
    }

    public void setCondominium(Condominium condominium)
    {
        this.condominium = condominium;
    }

    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public int getCpf()
    {
        return this.cpf;
    }

    public void setCpf(int cpf)
    {
        this.cpf = cpf;
    }

    public Boolean getAdm()
    {
        return this.adm;
    }

    public void setAdm(Boolean adm)
    {
        this.adm = adm;
    }

    public String getEmail()
    {
        return this.email;
    }

    public void setEmail(String email)
    {
        this.email = email;
    }

    public Set<AutenticationHistory> getAutenticationHistories()
    {
        return this.autenticationHistories;
    }

    public void setAutenticationHistories(Set<AutenticationHistory> autenticationHistories)
    {
        this.autenticationHistories = autenticationHistories;
    }

    public Set<PhoneNumberEmployee> getPhoneNumberEmployees()
    {
        return this.phoneNumberEmployees;
    }

    public void setPhoneNumberEmployees(Set<PhoneNumberEmployee> phoneNumberEmployees)
    {
        this.phoneNumberEmployees = phoneNumberEmployees;
    }

}
