package com.ssl.entities;
// default package
// Generated 28/02/2017 22:40:44 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EnumStatusKind generated by hbm2java
 */
@Entity
@Table(name = "enum_status_kind", schema = "dbo", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class EnumStatusKind implements java.io.Serializable
{

    private int id;
    private String name;
    private Set<ScheduledVisit> scheduledVisits = new HashSet<ScheduledVisit>(0);

    public EnumStatusKind()
    {
    }

    public EnumStatusKind(int id, String name)
    {
        this.id = id;
        this.name = name;
    }

    public EnumStatusKind(int id, String name, Set<ScheduledVisit> scheduledVisits)
    {
        this.id = id;
        this.name = name;
        this.scheduledVisits = scheduledVisits;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    @Column(name = "name", unique = true, nullable = false)
    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "enumStatusKind")
    public Set<ScheduledVisit> getScheduledVisits()
    {
        return this.scheduledVisits;
    }

    public void setScheduledVisits(Set<ScheduledVisit> scheduledVisits)
    {
        this.scheduledVisits = scheduledVisits;
    }

}
