package com.ssl.entities;
// Generated 28/02/2017 11:05:58 by Hibernate Tools 5.2.1.Final

/**
 * PhoneNumberCondominium generated by hbm2java
 */
public class PhoneNumberCondominium implements java.io.Serializable
{

    /**
     * 
     */
    private static final long serialVersionUID = 486321026701903662L;
    
    private int id;
    private Condominium condominium;
    private short countryCode;
    private short stateCode;
    private int number;

    public PhoneNumberCondominium()
    {
    }

    public PhoneNumberCondominium(int id, short countryCode, short stateCode, int number)
    {
        this.id = id;
        this.countryCode = countryCode;
        this.stateCode = stateCode;
        this.number = number;
    }

    public PhoneNumberCondominium(int id, Condominium condominium, short countryCode, short stateCode, int number)
    {
        this.id = id;
        this.condominium = condominium;
        this.countryCode = countryCode;
        this.stateCode = stateCode;
        this.number = number;
    }

    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    public Condominium getCondominium()
    {
        return this.condominium;
    }

    public void setCondominium(Condominium condominium)
    {
        this.condominium = condominium;
    }

    public short getCountryCode()
    {
        return this.countryCode;
    }

    public void setCountryCode(short countryCode)
    {
        this.countryCode = countryCode;
    }

    public short getStateCode()
    {
        return this.stateCode;
    }

    public void setStateCode(short stateCode)
    {
        this.stateCode = stateCode;
    }

    public int getNumber()
    {
        return this.number;
    }

    public void setNumber(int number)
    {
        this.number = number;
    }

}
