package com.ssl.entities;
// Generated 28/02/2017 11:05:58 by Hibernate Tools 5.2.1.Final

/**
 * PhoneNumberEmployee generated by hbm2java
 */
public class PhoneNumberEmployee implements java.io.Serializable
{

    /**
     * 
     */
    private static final long serialVersionUID = 1677036403259314970L;
    
    private int id;
    private Employee employee;
    private short countryCode;
    private short stateCode;
    private int number;

    public PhoneNumberEmployee()
    {
    }

    public PhoneNumberEmployee(int id, short countryCode, short stateCode, int number)
    {
        this.id = id;
        this.countryCode = countryCode;
        this.stateCode = stateCode;
        this.number = number;
    }

    public PhoneNumberEmployee(int id, Employee employee, short countryCode, short stateCode, int number)
    {
        this.id = id;
        this.employee = employee;
        this.countryCode = countryCode;
        this.stateCode = stateCode;
        this.number = number;
    }

    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    public Employee getEmployee()
    {
        return this.employee;
    }

    public void setEmployee(Employee employee)
    {
        this.employee = employee;
    }

    public short getCountryCode()
    {
        return this.countryCode;
    }

    public void setCountryCode(short countryCode)
    {
        this.countryCode = countryCode;
    }

    public short getStateCode()
    {
        return this.stateCode;
    }

    public void setStateCode(short stateCode)
    {
        this.stateCode = stateCode;
    }

    public int getNumber()
    {
        return this.number;
    }

    public void setNumber(int number)
    {
        this.number = number;
    }

}
