package com.ssl.entities;
// default package
// Generated 28/02/2017 22:40:44 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PhoneNumberVisitor generated by hbm2java
 */
@Entity
@Table(name = "phone_number_visitor", schema = "dbo")
public class PhoneNumberVisitor implements java.io.Serializable
{

    private int id;
    private Visitor visitor;
    private short countryCode;
    private short stateCode;
    private int number;

    public PhoneNumberVisitor()
    {
    }

    public PhoneNumberVisitor(int id, short countryCode, short stateCode, int number)
    {
        this.id = id;
        this.countryCode = countryCode;
        this.stateCode = stateCode;
        this.number = number;
    }

    public PhoneNumberVisitor(int id, Visitor visitor, short countryCode, short stateCode, int number)
    {
        this.id = id;
        this.visitor = visitor;
        this.countryCode = countryCode;
        this.stateCode = stateCode;
        this.number = number;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "visitor_id")
    public Visitor getVisitor()
    {
        return this.visitor;
    }

    public void setVisitor(Visitor visitor)
    {
        this.visitor = visitor;
    }

    @Column(name = "country_code", nullable = false)
    public short getCountryCode()
    {
        return this.countryCode;
    }

    public void setCountryCode(short countryCode)
    {
        this.countryCode = countryCode;
    }

    @Column(name = "state_code", nullable = false)
    public short getStateCode()
    {
        return this.stateCode;
    }

    public void setStateCode(short stateCode)
    {
        this.stateCode = stateCode;
    }

    @Column(name = "number_", nullable = false)
    public int getNumber()
    {
        return this.number;
    }

    public void setNumber(int number)
    {
        this.number = number;
    }

}
