package com.ssl.entities;
// Generated 28/02/2017 11:05:58 by Hibernate Tools 5.2.1.Final

/**
 * PhoneNumberVisitor generated by hbm2java
 */
public class PhoneNumberVisitor implements java.io.Serializable
{

    /**
     * 
     */
    private static final long serialVersionUID = 487958342597775583L;
    
    private int id;
    private Visitor visitor;
    private short countryCode;
    private short stateCode;
    private int number;

    public PhoneNumberVisitor()
    {
    }

    public PhoneNumberVisitor(int id, short countryCode, short stateCode, int number)
    {
        this.id = id;
        this.countryCode = countryCode;
        this.stateCode = stateCode;
        this.number = number;
    }

    public PhoneNumberVisitor(int id, Visitor visitor, short countryCode, short stateCode, int number)
    {
        this.id = id;
        this.visitor = visitor;
        this.countryCode = countryCode;
        this.stateCode = stateCode;
        this.number = number;
    }

    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    public Visitor getVisitor()
    {
        return this.visitor;
    }

    public void setVisitor(Visitor visitor)
    {
        this.visitor = visitor;
    }

    public short getCountryCode()
    {
        return this.countryCode;
    }

    public void setCountryCode(short countryCode)
    {
        this.countryCode = countryCode;
    }

    public short getStateCode()
    {
        return this.stateCode;
    }

    public void setStateCode(short stateCode)
    {
        this.stateCode = stateCode;
    }

    public int getNumber()
    {
        return this.number;
    }

    public void setNumber(int number)
    {
        this.number = number;
    }

}
