package com.ssl.entities;
// Generated 28/02/2017 11:05:58 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ScheduledVisit generated by hbm2java
 */
public class ScheduledVisit implements java.io.Serializable
{

    /**
     * 
     */
    private static final long serialVersionUID = -6242147895179566235L;
    
    private int id;
    private Condominium condominium;
    private EnumStatusKind enumStatusKind;
    private Userr userr;
    private Visitor visitor;
    private Date visitDate;
    private String kind;
    private Boolean hasVehicle;
    private Set<ServiceProvision> serviceProvisions = new HashSet<ServiceProvision>(0);

    public ScheduledVisit()
    {
    }

    public ScheduledVisit(int id, Date visitDate)
    {
        this.id = id;
        this.visitDate = visitDate;
    }

    public ScheduledVisit(int id, Condominium condominium, EnumStatusKind enumStatusKind, Userr userr, Visitor visitor,
            Date visitDate, String kind, Boolean hasVehicle, Set<ServiceProvision> serviceProvisions)
    {
        this.id = id;
        this.condominium = condominium;
        this.enumStatusKind = enumStatusKind;
        this.userr = userr;
        this.visitor = visitor;
        this.visitDate = visitDate;
        this.kind = kind;
        this.hasVehicle = hasVehicle;
        this.serviceProvisions = serviceProvisions;
    }

    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    public Condominium getCondominium()
    {
        return this.condominium;
    }

    public void setCondominium(Condominium condominium)
    {
        this.condominium = condominium;
    }

    public EnumStatusKind getEnumStatusKind()
    {
        return this.enumStatusKind;
    }

    public void setEnumStatusKind(EnumStatusKind enumStatusKind)
    {
        this.enumStatusKind = enumStatusKind;
    }

    public Userr getUserr()
    {
        return this.userr;
    }

    public void setUserr(Userr userr)
    {
        this.userr = userr;
    }

    public Visitor getVisitor()
    {
        return this.visitor;
    }

    public void setVisitor(Visitor visitor)
    {
        this.visitor = visitor;
    }

    public Date getVisitDate()
    {
        return this.visitDate;
    }

    public void setVisitDate(Date visitDate)
    {
        this.visitDate = visitDate;
    }

    public String getKind()
    {
        return this.kind;
    }

    public void setKind(String kind)
    {
        this.kind = kind;
    }

    public Boolean getHasVehicle()
    {
        return this.hasVehicle;
    }

    public void setHasVehicle(Boolean hasVehicle)
    {
        this.hasVehicle = hasVehicle;
    }

    public Set<ServiceProvision> getServiceProvisions()
    {
        return this.serviceProvisions;
    }

    public void setServiceProvisions(Set<ServiceProvision> serviceProvisions)
    {
        this.serviceProvisions = serviceProvisions;
    }

}
