package com.ssl.entities;
// default package
// Generated 28/02/2017 22:40:44 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ScheduledVisit generated by hbm2java
 */
@Entity
@Table(name = "scheduled_visit", schema = "dbo")
public class ScheduledVisit implements java.io.Serializable
{

    private int id;
    private Condominium condominium;
    private EnumStatusKind enumStatusKind;
    private Userr userr;
    private Visitor visitor;
    private Date visitDate;
    private String kind;
    private Boolean hasVehicle;
    private Set<ServiceProvision> serviceProvisions = new HashSet<ServiceProvision>(0);

    public ScheduledVisit()
    {
    }

    public ScheduledVisit(int id, Date visitDate)
    {
        this.id = id;
        this.visitDate = visitDate;
    }

    public ScheduledVisit(int id, Condominium condominium, EnumStatusKind enumStatusKind, Userr userr, Visitor visitor,
            Date visitDate, String kind, Boolean hasVehicle, Set<ServiceProvision> serviceProvisions)
    {
        this.id = id;
        this.condominium = condominium;
        this.enumStatusKind = enumStatusKind;
        this.userr = userr;
        this.visitor = visitor;
        this.visitDate = visitDate;
        this.kind = kind;
        this.hasVehicle = hasVehicle;
        this.serviceProvisions = serviceProvisions;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "condominium_id")
    public Condominium getCondominium()
    {
        return this.condominium;
    }

    public void setCondominium(Condominium condominium)
    {
        this.condominium = condominium;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "status")
    public EnumStatusKind getEnumStatusKind()
    {
        return this.enumStatusKind;
    }

    public void setEnumStatusKind(EnumStatusKind enumStatusKind)
    {
        this.enumStatusKind = enumStatusKind;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "userr_requester_id")
    public Userr getUserr()
    {
        return this.userr;
    }

    public void setUserr(Userr userr)
    {
        this.userr = userr;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "visitor_id")
    public Visitor getVisitor()
    {
        return this.visitor;
    }

    public void setVisitor(Visitor visitor)
    {
        this.visitor = visitor;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "visit_date", nullable = false, length = 29)
    public Date getVisitDate()
    {
        return this.visitDate;
    }

    public void setVisitDate(Date visitDate)
    {
        this.visitDate = visitDate;
    }

    @Column(name = "kind")
    public String getKind()
    {
        return this.kind;
    }

    public void setKind(String kind)
    {
        this.kind = kind;
    }

    @Column(name = "has_vehicle")
    public Boolean getHasVehicle()
    {
        return this.hasVehicle;
    }

    public void setHasVehicle(Boolean hasVehicle)
    {
        this.hasVehicle = hasVehicle;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "scheduledVisit")
    public Set<ServiceProvision> getServiceProvisions()
    {
        return this.serviceProvisions;
    }

    public void setServiceProvisions(Set<ServiceProvision> serviceProvisions)
    {
        this.serviceProvisions = serviceProvisions;
    }

}
