package com.ssl.entities;
// default package
// Generated 28/02/2017 22:40:44 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ServiceProvision generated by hbm2java
 */
@Entity
@Table(name = "service_provision", schema = "dbo")
public class ServiceProvision implements java.io.Serializable
{

    private int id;
    private ScheduledVisit scheduledVisit;
    private String company;
    private String description;

    public ServiceProvision()
    {
    }

    public ServiceProvision(int id, String company)
    {
        this.id = id;
        this.company = company;
    }

    public ServiceProvision(int id, ScheduledVisit scheduledVisit, String company, String description)
    {
        this.id = id;
        this.scheduledVisit = scheduledVisit;
        this.company = company;
        this.description = description;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "scheduled_visit_id")
    public ScheduledVisit getScheduledVisit()
    {
        return this.scheduledVisit;
    }

    public void setScheduledVisit(ScheduledVisit scheduledVisit)
    {
        this.scheduledVisit = scheduledVisit;
    }

    @Column(name = "company", nullable = false)
    public String getCompany()
    {
        return this.company;
    }

    public void setCompany(String company)
    {
        this.company = company;
    }

    @Column(name = "description")
    public String getDescription()
    {
        return this.description;
    }

    public void setDescription(String description)
    {
        this.description = description;
    }

}
