package com.ssl.entities;
// Generated 28/02/2017 11:05:58 by Hibernate Tools 5.2.1.Final

/**
 * ServiceProvision generated by hbm2java
 */
public class ServiceProvision implements java.io.Serializable
{

    /**
     * 
     */
    private static final long serialVersionUID = 3139813417484099208L;
    
    private int id;
    private ScheduledVisit scheduledVisit;
    private String company;
    private String description;

    public ServiceProvision()
    {
    }

    public ServiceProvision(int id, String company)
    {
        this.id = id;
        this.company = company;
    }

    public ServiceProvision(int id, ScheduledVisit scheduledVisit, String company, String description)
    {
        this.id = id;
        this.scheduledVisit = scheduledVisit;
        this.company = company;
        this.description = description;
    }

    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    public ScheduledVisit getScheduledVisit()
    {
        return this.scheduledVisit;
    }

    public void setScheduledVisit(ScheduledVisit scheduledVisit)
    {
        this.scheduledVisit = scheduledVisit;
    }

    public String getCompany()
    {
        return this.company;
    }

    public void setCompany(String company)
    {
        this.company = company;
    }

    public String getDescription()
    {
        return this.description;
    }

    public void setDescription(String description)
    {
        this.description = description;
    }

}
