package com.ssl.entities;
// default package
// Generated 28/02/2017 22:40:44 by Hibernate Tools 5.2.1.Final

import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * Vehicle generated by hbm2java
 */
@Entity
@Table(name = "vehicle", schema = "dbo")
@DynamicInsert
@DynamicUpdate
public class Vehicle implements Serializable
{

    /**
     * 
     */
    private static final long serialVersionUID = -6697219468314563361L;
    
    private int id;
    private Userr userr;
    private String model;
    private String color;
    private String licensePlate;

    public Vehicle()
    {
    }

    public Vehicle(int id, String model, String color, String licensePlate)
    {
        this.id = id;
        this.model = model;
        this.color = color;
        this.licensePlate = licensePlate;
    }

    public Vehicle(int id, Userr userr, String model, String color, String licensePlate)
    {
        this.id = id;
        this.userr = userr;
        this.model = model;
        this.color = color;
        this.licensePlate = licensePlate;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY, cascade=CascadeType.ALL)
    @JoinColumn(name = "userr_id")
    public Userr getUserr()
    {
        return this.userr;
    }

    public void setUserr(Userr userr)
    {
        this.userr = userr;
    }

    @Column(name = "model", nullable = false)
    public String getModel()
    {
        return this.model;
    }

    public void setModel(String model)
    {
        this.model = model;
    }

    @Column(name = "color", nullable = false)
    public String getColor()
    {
        return this.color;
    }

    public void setColor(String color)
    {
        this.color = color;
    }

    @Column(name = "license_plate", nullable = false, unique = true)
    public String getLicensePlate()
    {
        return this.licensePlate;
    }

    public void setLicensePlate(String licensePlate)
    {
        this.licensePlate = licensePlate;
    }

}
