package com.ssl.entities;
// Generated 28/02/2017 11:05:58 by Hibernate Tools 5.2.1.Final

/**
 * Vehicle generated by hbm2java
 */
public class Vehicle implements java.io.Serializable
{

    /**
     * 
     */
    private static final long serialVersionUID = -6697219468314563361L;
    
    private int id;
    private Userr userr;
    private String model;
    private String color;
    private String licensePlate;

    public Vehicle()
    {
    }

    public Vehicle(int id, String model, String color, String licensePlate)
    {
        this.id = id;
        this.model = model;
        this.color = color;
        this.licensePlate = licensePlate;
    }

    public Vehicle(int id, Userr userr, String model, String color, String licensePlate)
    {
        this.id = id;
        this.userr = userr;
        this.model = model;
        this.color = color;
        this.licensePlate = licensePlate;
    }

    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    public Userr getUserr()
    {
        return this.userr;
    }

    public void setUserr(Userr userr)
    {
        this.userr = userr;
    }

    public String getModel()
    {
        return this.model;
    }

    public void setModel(String model)
    {
        this.model = model;
    }

    public String getColor()
    {
        return this.color;
    }

    public void setColor(String color)
    {
        this.color = color;
    }

    public String getLicensePlate()
    {
        return this.licensePlate;
    }

    public void setLicensePlate(String licensePlate)
    {
        this.licensePlate = licensePlate;
    }

}
