package com.ssl.entities;
// default package
// Generated 28/02/2017 22:40:44 by Hibernate Tools 5.2.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * Visitor generated by hbm2java
 */
@Entity
@Table(name = "visitor", schema = "dbo")
@DynamicInsert
@DynamicUpdate
public class Visitor implements Serializable
{

    /**
     * 
     */
    private static final long serialVersionUID = -6842087891443867304L;
    
    private int id;
    private Condominium condominium;
    private String name;
    private Set<ScheduledVisit> scheduledVisits = new HashSet<ScheduledVisit>(0);
    private Set<PhoneNumberVisitor> phoneNumberVisitors = new HashSet<PhoneNumberVisitor>(0);

    public Visitor()
    {
    }

    public Visitor(int id, String name)
    {
        this.id = id;
        this.name = name;
    }

    public Visitor(int id, Condominium condominium, String name, Set<ScheduledVisit> scheduledVisits,
            Set<PhoneNumberVisitor> phoneNumberVisitors)
    {
        this.id = id;
        this.condominium = condominium;
        this.name = name;
        this.scheduledVisits = scheduledVisits;
        this.phoneNumberVisitors = phoneNumberVisitors;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "condominium_id")
    public Condominium getCondominium()
    {
        return this.condominium;
    }

    public void setCondominium(Condominium condominium)
    {
        this.condominium = condominium;
    }

    @Column(name = "name", nullable = false)
    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "visitor")
    public Set<ScheduledVisit> getScheduledVisits()
    {
        return this.scheduledVisits;
    }

    public void setScheduledVisits(Set<ScheduledVisit> scheduledVisits)
    {
        this.scheduledVisits = scheduledVisits;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "visitor")
    public Set<PhoneNumberVisitor> getPhoneNumberVisitors()
    {
        return this.phoneNumberVisitors;
    }

    public void setPhoneNumberVisitors(Set<PhoneNumberVisitor> phoneNumberVisitors)
    {
        this.phoneNumberVisitors = phoneNumberVisitors;
    }

}
