package com.ssl.entities;
// Generated 28/02/2017 11:05:58 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Visitor generated by hbm2java
 */
public class Visitor implements java.io.Serializable
{

    /**
     * 
     */
    private static final long serialVersionUID = -6842087891443867304L;
    
    private int id;
    private Condominium condominium;
    private String name;
    private Set<ScheduledVisit> scheduledVisits = new HashSet<ScheduledVisit>(0);
    private Set<PhoneNumberVisitor> phoneNumberVisitors = new HashSet<PhoneNumberVisitor>(0);

    public Visitor()
    {
    }

    public Visitor(int id, String name)
    {
        this.id = id;
        this.name = name;
    }

    public Visitor(int id, Condominium condominium, String name, Set<ScheduledVisit> scheduledVisits,
            Set<PhoneNumberVisitor> phoneNumberVisitors)
    {
        this.id = id;
        this.condominium = condominium;
        this.name = name;
        this.scheduledVisits = scheduledVisits;
        this.phoneNumberVisitors = phoneNumberVisitors;
    }

    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    public Condominium getCondominium()
    {
        return this.condominium;
    }

    public void setCondominium(Condominium condominium)
    {
        this.condominium = condominium;
    }

    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public Set<ScheduledVisit> getScheduledVisits()
    {
        return this.scheduledVisits;
    }

    public void setScheduledVisits(Set<ScheduledVisit> scheduledVisits)
    {
        this.scheduledVisits = scheduledVisits;
    }

    public Set<PhoneNumberVisitor> getPhoneNumberVisitors()
    {
        return this.phoneNumberVisitors;
    }

    public void setPhoneNumberVisitors(Set<PhoneNumberVisitor> phoneNumberVisitors)
    {
        this.phoneNumberVisitors = phoneNumberVisitors;
    }

}
